### ISSUE TITLE
Question: How do I stop a subscription based on message content?

### ISSUE THREAD

**Issue by marcelonyc** [jasonrbriggs/stomp.py#183]
I am looking for a way to detect one message in a queue and then continue the main program. I would appreciate any suggestions.

class order_check_listener(stomp.ConnectionListener):
   def __init__(self,order):
        self.order=order
        
    def on_message(self, headers, message):
        message=message.replace("'","\"")
        message=json.loads(message)
        if 'id' in message:
            if message['id'] != self.order:
      #I want this to be the last message I read
                print "I want to stop monitoring the queue"  

order=123
queue.set_listener('', order_check_listener(order))
queue.start()
queue.connect('xxxx','xxxxxxxx')

      # When I get a message for order 123 I want to stop monitoring the queue.
queue.subscribe('/queue/orders', 1) 
time.sleep(20)   ## I get stuck waiting for the sleep to end
...More code after this

**Comment by jasonrbriggs** [comment]
Well you could do something like this:

```python
class order_check_listener(stomp.ConnectionListener):
    def __init__(self, conn, order):
        self.conn = conn
        self.order=order
    def on_message(self, headers, message):
        message=message.replace("'","\"")
        message=json.loads(message)
        if 'id' in message:
            if message['id'] == self.order:
                ...do some additional processing here...
                self.conn.remove_listener(self.order) 
```

...and then...

```python
order=123
queue.set_listener(order, order_check_listener(queue, order))
```

But to be honest not entirely sure I understand the use case.  Not sure it's scalable to have a listener per order, if that's what you're doing, because every listener has to extract the message and then process if it matches.  You'd be better to have a single listener for all orders, extract the relevant info from the message, and then call something else to process (for example, using asyncio and concurrent.futures would be one approach).

**Comment by marcelonyc** [comment]
Thank you for your feedback. I do see the faults in my architecture. I will look into your recommendations.
