### ISSUE TITLE
Best practices for long-running listeners? 

### ISSUE THREAD

**Issue by bkjones** [jasonrbriggs/stomp.py#206]
I'm writing a stomp consumer and I have something that more or less works, but am wondering if I've missed something, or if what I've done actually is the recommended way to have a long-running listener. 

```
if __name__ == '__main__':
    conn = connect_and_subscribe([('localhost', 61613)], MyStompConsumer(), 'admin', 'password', '/queue/test')
    while conn.is_connected():
        time.sleep(2)
```

If I put a send() call before the time.sleep, it makes a nice loop that allows me to test that things are working, so that's good. 

I'm also wondering, though, if/how I can use multiple listeners on a connection. Can I (and is it advisable to) register, for example, both the heartbeat listener and the stats listener separately on the same connection and use the same infinite loop above? 

Thanks for any input - just looking for advice on implementation more complicated than the examples (which were good for quick functional testing and are much appreciated as well).

**Comment by alexeygrigorev** [comment]
What I do is using a blocking queue (`import queue`), make listener add to the queue, and pull from that queue in a `while True` loop.

Not sure if it's the best way though

**Comment by jasonrbriggs** [comment]
If you're talking about just a couple of listeners then I don't think it makes a lot of difference. The listener notification loop isn't particularly optimal (it just iterates over the registered listeners and checks for an on_<event> method on each on - it could be better, but tidying that up is something I was putting off until ending support for Python2, and then look at replacing the loops with an asyncio event loop (or something like that -- still a back-of-the-head thought rather than an actual plan). Certainly if you're only registering a few listeners, I still don't see it making a huge amount of difference unless the listener methods are long running... at which point it really isn't the way to go.

**Comment by emakarov** [comment]
@jasonrbriggs would be nice to have asyncio support

**Comment by HWiese1980** [comment]
Has there been some development here? 

I have a listener that just executes `asyncio.get_event_loop().run_forever()` in the main thread at the end, and it seems like somehow this is throwing the task into a cpu hogging loop for some reason.
