### ISSUE TITLE
Synchronous consumer interface

### ISSUE THREAD

**Issue by aparamon** [jasonrbriggs/stomp.py#218]
Currently, `stomp.py` provides only asynchronous interface for message consumption. However, often synchronous interface may be preferable, for more clear code (esp. in case of bi-directional communication).

Synchronous processing can be achieved via helper class
````py
class SyncListener(stomp.ConnectionListener):
    def __init__(self, buf):
        super().__init__()
        self.buf = buf
    def on_connected(self, headers, body):
        self.buf.put(('connected', headers, body))
    def on_disconnected(self):
        self.buf.put(('disconnected', None, None))
    def on_message(self, headers, body):
        self.buf.put(('message', headers, body))
    def on_receipt(self, headers, body):
        self.buf.put(('receipt', headers, body))
    def on_error(self, headers, body):
        self.buf.put(('error', headers, body))
    def on_heartbeat(self):
        self.buf.put(('heartbeat', None, None))
````
like this:
````py
events = queue.Queue()
conn.set_listener('', SyncListener(events))

while True:
    (type, headers, body) = events.get(timeout=10)
    if type == 'message':
        ...
    elif type == 'disconnected':
        break
````
But this feels extremely over-engineered: the threaded wrapper should be built around the simple synchronous interface, not vice versa.

It is proposed to implement `Connection.get(self, timeout=None)` method returning tuples `(type, headers, body)` asynchronously.

Additionally, it might be more *pythonic* to raise exception on receiving 'error' frame rather than returning `('error', headers, body)`.

**Comment by aparamon** [comment]
Alternative asynchronous model based on coroutines can be achieved easily replacing `queue.Queue` with
[asyncio.Queue](https://docs.python.org/3/library/asyncio-queue.html#asyncio.Queue)

**Comment by rtista** [comment]
I'd very much like to use this library, but unfortunately, I require a synchronous client in order to achieve better performance on what I'm building. Could anyone tell me if this thread is being investigated?

**Comment by rtista** [comment]
@jasonrbriggs could you help me with some directives as to how to implement this functionality?

From what I've seen, and please correct me if I am wrong, in order to achieve this functionality, I would need to implement a get(self, timeout=0) method in the protocol.py module (in Protocol11 and Protocol10 classes), which would call a receive_frame(self) in the transport.py module. The receive_frame would implement most of the logic in the __read(self) method (also in the transport module) but only read 1 frame from the socket at a time and returning it or None if no frame is available.

I believe this receive_frame method could even be used in order to remove some code from the complex __read method. If a positional non-mandatory argument "pos" was provided to ensure that the loop under __read was able to continue and gather all the frames. I am however unsure about this as I've still not worked much with socket networking in python.

Am I terribly wrong about this? Do you believe this functionality requires to much refactoring of the code or is even impossible to implement taking into account the basis of the code?

**Comment by madkote** [comment]
@rtista you need to process data in sync or consume?

processing is simple. consume would be difficult, because of the threading overkill.

**Comment by rtista** [comment]
@madkote practically I would like an interface such as multiprocessing.Queue in the python standard library where you are able to retrieve items from the queue one by one and work from there. This is basically how a synchronous consumer interface works, by making no assumptions about your implementation, since consumers retrieve messages from the message broker on the contrary of asynchronous consumers in which the broker delivers the messages to them.

As @aparamon mentioned, I'm facing a situation where I need to retrieve a message from the broker, do something with it, send 2 messages to 2 different broker queues and only then acknowledge the message. This is do-able via the asynchronous listener interface you provide, but I feel the code becomes more confusing, and i.e. assumes that you'd like to use threads instead of processes.

If you require an example, there's a STOMP implementation (https://github.com/nikipore/stompest) which provides both a synchronous and asynchronous interface, yet, it is without active maintenance and I would like to use something more robust from that point of view.

**Comment by madkote** [comment]
@rtista so you need sync processing. I had done similar example too - get message, POST, ack.
* get message
* do something with it
* ack
You need to ensure it is single threaded (main thread).


The only trick, is to write a good client on top of this lib.

**Comment by rtista** [comment]
@madkote exactly! I was a bit confused by what "processing" and "consuming" meant. Do you have any idea if what I proposed above would be suitable as an implementation? By which I mean simply abstracting some code from the __read function into another function in the same module and then calling that function from a get method in the protocol module.

Or do you mean that due to the way the code is written in the transport module supporting a  synchronous implementation is not possible?

**Comment by madkote** [comment]
@rtista I did some deep scan of the module in the past. Now, I wrote a client to subscribe (with callback) or to publish. Both also handling clusters and reconnection.

to you problem: as far I understood, you consume a message, process it, send ack. then next message.

=> you need one consumer. the code can be written on top of library.

=> Another option is to collect messages in a queue, process them and send another messages with result (ok, error, ...) so that it can be verified. IMHO, this is better approach.

**Comment by rtista** [comment]
@madkote Basically what I want is to implement the consumer cycle myself, I only need the connection object to provide me with a get method to retrieve one message from the broker, which I will then process, a ack method to acknowledge the message and then do this in a cycle which I have defined.
