### ISSUE TITLE
Messages don't send by default as text

### ISSUE THREAD

**Issue by arsalankhalid** [jasonrbriggs/stomp.py#299]
Hi Jason, 

I've been using stomp py for sending messages to a java broker in an instance far far away. 
Basically connectivity is good, and messages are being received, but they're being interpreted as Binary. Why doesn't the following send JMS TextMessages to my broker/receiver?

            `conn.send(body=payload, content_type='text/plain', destination=destination, headers={'content-length': 7500})`

I've also tried with content-length being removed... yet nothing works, my receiver logic still receives binary blobs, How do I fix this?

**Comment by jasonrbriggs** [comment]
I think it might be an issue with the broker.  I added a quick unit test to double-check the content_type param is being past as expected - setting with "text/something" to validate it's not getting a default value -- and it looks good to me:

```
DEBUG    stomp.py:transport.py:268 Sending frame: [b'SEND', b'\n', b'content-length:30\n', b'content-type:text/something\n', b'destination:/test/queue\n', b'\n', b'test message with content type', b'\x00']
```

So I don't think it's stomp.py causing the problem here.

**Comment by arsalankhalid** [comment]
Thanks! We just got around it be deserializing the blob, but if you've proven it with a test then you may be right...
