### ISSUE TITLE
how can i set 'activemq.prefetchSize': 0 on subscribe the activemq

### ISSUE THREAD

**Issue by dreamjole** [jasonrbriggs/stomp.py#312]
when i pass {'activemq.prefetchSize': 0} onsubscribe， the consumer can not receive any message from the activeMq broker

@jasonrbriggs @Soarnsky 
on connect pass:
```headers={'activemq.prefetchSize': <SOME_VALUE_INT>}```

so it can be closed.

_Originally posted by @madkote in https://github.com/jasonrbriggs/stomp.py/issues/289#issuecomment-595155003_

**Comment by jasonrbriggs** [comment]
Do you have any logs from activemq that show what's going on?  I've tried with activemq running in a docker image and I can't get it logging anything useful (annoyingly), so I can't see if there's an error on the server side.  Certainly if I turn on debug logging in stomp.py, I can see nothing is returned after subscribe, so that implies an issue with activemq.  By comparison, activemq-artemis apparently uses consumerWIndowSIze (https://stackoverflow.com/questions/51842587/apache-activemq-artemis-equivalent-of-prefetch-policy#51843746) -- setting that seems not to break.  So, don't see any evidence of this being a stomp.py issue.

**Comment by jasonrbriggs** [comment]
More evidence this is an activeMQ issue.  If I set prefetch to 1, I get a response when sending to a queue.  If I set it to 0, I don't get a response.  I can also send random headers in a subscribe call with no issues.  I'm closing this issue for the moment - I don't believe this is anything stomp.py can address.
