### ISSUE TITLE
Pls allow stomp.py to connect to websocket url like ws.myhost.com/stomp/

### ISSUE THREAD

**Issue by hihellobolke** [jasonrbriggs/stomp.py#32]
Currently stomp.py accept host and port but not path to url. This would make it more awesome!

Thank!

**Comment by jasonrbriggs** [comment]
Not something I have a need for really. Nor entirely sure what the benefit would be.  

It is relatively straightforward to implement a new transport for stomp (see https://github.com/jasonrbriggs/stomp.py/blob/master/stomp/adapter/multicast.py), so you could implement yourself if it's something you really need.

**Comment by imperialguy** [comment]
> Currently stomp.py accept host and port but not path to url. This would make it more awesome!
> 
> Thank!

Did you end up implementing this yourself? If so, could you please share it?

**Comment by imperialguy** [comment]
> Not something I have a need for really. Nor entirely sure what the benefit would be.
> 
> It is relatively straightforward to implement a new transport for stomp (see https://github.com/jasonrbriggs/stomp.py/blob/master/stomp/adapter/multicast.py), so you could implement yourself if it's something you really need.

This feature would be particularly really useful when we can't open the STOMP port to other machines. Using this feature, we will be able to connect using the websocket path instead of host and port. We can a proxy server that will redirect the websocket internally to the STOMP port. That way, the port doesn't need to opened. 

So, it will look something like this:

```
c = stomp.Connection('ws://localhost/path/to/websocket/endpoint')
```

Instead of 
c = stomp.Connection([('localhost', 62613)])
